config/routes.rb
RailsPadrao::Application.routes.draw do


  resources :categorias


  resources :custos

  resources :arquivos


  resources :cursos do
    member do
      get :download
    end
  end

  resources :relatorios do
    collection do
      get :relatorio_fase_custos
      post :exporta_relatorio
    end
  end


  root :to => 'application#home'
  authenticated :user do
    root :to => 'application#home'
  end
  resources :noticias do
    member do
      get :like
      get :dislike
      get :remover_voto
      post :criar_comentario
    end

    collection do
      get :feed
      get :buscar_tag
    end
  end

  devise_for :users do
    get 'users/:id/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'

  end

  resources :users do
    collection do
      get 'novo_usuario_manual'
      post 'cria_usuario_manualmente'
    end
  end

  resource :users, :only => [:edit] do
    member do
      post ':id/atualizar' => 'users#atualiza_usuario_com_senha', :as => "atualiza_usuario_com_senha"
    end
  end

  resources :roles do
    collection do
      get 'associar_permissao'
    end
  end

  resources :permissions

  resources :permission_role do
    collection do
      post 'remove_permissao_ajax'
      post 'adiciona_permissao_ajax'
    end
  end

  resources :fases do
    collection do
      get 'pesquisar'
    end

  end


end

app/controllers/fases_controller.rb
#encoding: utf-8
class FasesController < ApplicationController

  load_and_authorize_resource

  before_filter :carrega_dados, :only => [:index,:pesquisar]



  def index
    @fases = Fase.paginate(:page => params[:page], :per_page => 25)
    respond_to do |format|
      format.html
      format.js { render :partial => 'fase_index' }
    end
  end

  def carrega_dados
    @fase_nova = Fase.new
    @cursos = Curso.ordenado_por_nome.all.collect { |u| [u.nome, u.id] }
  end

  def show
    @categoria_nova = Categoria.new
    @fase = Fase.find(params[:id])
    @custos_associados = Custo.paginate(:page => params[:page], :per_page => 5)
    @custo_novo = Custo.new
    @custo_total = @fase.custos.sum('(valor*quantidade)+(valor*quantidade*tributo)/100')
#    carregarGraficos
    @custo_excedido = @custo_total.to_i > @fase.orcamento.to_i ? true : false
    @valor_excedido = @custo_total.to_i - @fase.orcamento.to_i
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @fase }
    end
  end

  def new
    @fase = Fase.new

  end

  def edit
    @fase = Fase.find(params[:id])
  end

  def create
    #Não consegui achar forma melhor de tirar o
    params[:fase][:orcamento] = params[:fase][:orcamento].split('.').join.split(',').join
    @fase = Fase.new(params[:fase])
    if @fase.save
      redirect_to :back, :notice => "Fase criada com sucesso"
    else
      redirect_to :back, :alert => "Não foi possível criar a fase '#{@fase.descricao}'. Erro: #{@fase.errors.full_message.to_s}"
    end
  end

  def update
    @fase = Fase.find(params[:id])
    params[:fase][:orcamento] = params[:fase][:orcamento].split('.').join.split(',').join
    if @fase.update_attributes(params[:fase])
      redirect_to fases_path, :notice => "Fase atualizada com sucesso"
    else
      redirect_to fases_path, :alert => "Não foi possível atualizar a fase '#{@fase.descricao}'. Erro: #{@fase.errors.full_message.to_s}"
    end
  end

  def destroy

    fase = Fase.find(params[:id])

    fase.destroy
    redirect_to fases_path, :notice => "Fase '#{fase.descricao}' removida."

  end

  def pesquisar
    valor = params[:filtro].split('.').join.split(',').join

    #Busca por Datas
    if !params[:inicio_periodo].blank? || !params[:fim_periodo].blank?
       @fases = Fase.comecando(params[:inicio_periodo].to_date.to_s).scoped if !params[:inicio_periodo].blank?
       @fases = Fase.finalizando(params[:fim_periodo].to_date.to_s).scoped if !params[:fim_periodo].blank?
       @fases = @fases.paginate(:page => params[:page], :per_page => 25) if @fases.any?

    else
    #Busca por VALOR
    #Se for numero, procura no orcamento.
    if !(valor.to_s.match(/\A[+-]?\d+?(\.\d+)?\Z/)).nil?  && !valor.blank?
      @fases = Fase.joins(:curso).where("fases.orcamento = ?",valor).paginate(:page => params[:page], :per_page => 25)
    #VALOR E DATAS em branco?! Então busco todos.
    elsif valor.blank? && (params[:inicio_periodo].blank? && params[:fim_periodo].blank?)
      @fases = Fase.paginate(:page => params[:page], :per_page => 25)
    else
      #É um valor valido para procurar
      @fases = Fase.joins(:curso).where("cursos.nome like ? or fases.descricao like ?",'%'+valor+'%','%'+valor+'%').paginate(:page => params[:page], :per_page => 25)
    end

    end
    @termo = params[:filtro]
    respond_to do |format|
      format.html { render "index"}
    end


  end

  def carregarGraficos
    @categorias = @fase.custos.each do |c| l c.dt_referencia.to_date end
    @chart2 = LazyHighCharts::HighChart.new('column') do |f|
      f.title(:text => "Population vs GDP For 5 Big Countries [2009]")
      f.xAxis(:categories => [@categorias.collect{|c| p ("'" + (l c.dt_referencia.to_date).to_s + "'")}])
      @resultado = @fase.custos.select("categoria_id,count(1) as qtd").group("categoria_id")
      f.series(:name => @fase.custos.select("categoria_id,count(1) as qtd").group("categoria_id"), :data => @resultado)

      f.yAxis [
                  {:title => {:text => "GDP in Billions", :margin => 70} },
                  {:title => {:text => "Population in Millions"}, :opposite => true},
              ]

      f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
      f.chart({:defaultSeriesType=>"column"})
    end
  end

end

app/views/fases/_fase.html.erb
<div id="edit-fase-<%= fase.id %>" aria-hidden="true" role="dialog" aria-labelledby="meuModal_<%= fase.id %>" class="modal" style="display: none;">
  <%= simple_form_for(fase, :url => fase_path(fase),:html => {:class => 'form-horizontal' })  do |f| %>
    <div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3 class="modal-title" id="meuModal_<%= fase.id %>">Editar</h3>
    </div>
    <div class="modal-body">
      <div class="form-group">
        <div class="form-group">

          <%= render :partial => 'form',:locals => { :f => f, :role => f } %>

    </div>
    <div class="modal-footer">
      <%= f.submit "Alterar", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Fechar</a>
    </div>
  <% end %>
</div>
</div>
</div>
</div>
</div>

<script type="text/javascript">
    $( document ).ready(function() {
        $('#edit-fase-<%= fase.id %>').ketchup();


    });

</script>

app/views/fases/_fase_index.html.erb
#encoding: utf-8
<% @fases.each do |fase| %>
    <tr>
      <td><%= fase.curso.nome %></td>
      <td><%= fase.descricao %></td>
      <td><div id="fase_orcamento_show"><%= fase.orcamento %></div></td>
      <td>
        <a data-toggle="modal" class="btn btn-xs btn-default" href="#edit-fase-<%= fase.id %>"  type="button">Editar</a>
        <%= render fase%>
      </td>
      <td><%= link_to("Remover", fases_path(fase), :style => "margin-top:-7px;", :data => { :confirm => "Você tem certeza?" }, :method => :delete, :class => 'btn btn-xs btn-danger') %></td>
    </tr>
<% end %>
  <%= will_paginate @fases,:renderer => BootstrapPagination::Rails%>

app/views/fases/_form.html.erb
# encoding: utf-8
<%
   @fase = f.object
   %>
    <fieldset>

      <div class="form-group">
        <%= f.label :descricao, "Nome:",:class => "col-xs-6 col-sm-3 col-md-2 control-label" %>
        <div class="col-sm-7">
          <%= f.text_field :descricao, :class => "form-control","data-validate" => "validate(required) on(submit)", :title => "Nome da fase deve ser fornecida",:placeholder => "Insira o nome da fase", :value => (@fase.descricao if (!@fase.nil? && !@fase.new_record?))%>
          <p class="help-block" style="font-size: 11px;">Insira o nome da fase. Obrigatório.</p>
        </div>
      </div>

      <%#= f.fields_for :curso do |f| %>
      <div class="form-group">
        <%= f.label :curso_id,:class => "col-xs-6 col-sm-3 col-md-2 control-label" %>
        <div class="col-sm-7">
          <%= f.collection_select :curso_id,Curso.all,:id,:nome,{:include_blank => "Selecione uma opção" }, {"data-validate" => "validate(select)",:class => "form-control"} %>
          <p class="help-block" style="font-size: 11px;">Insira o curso do custo. Obrigatório.</p>
        </div>
      </div>
      <%#end%>
      <div class="form-group">
        <%= f.label :orcamento,:class => "col-xs-6 col-sm-3 col-md-2 control-label" %>
        <div class="col-sm-7">
          <%= f.text_field :orcamento, :class => "form-control","data-validate" => "validate(required) on(submit)", :title => "O orçamento deve ser inserido", :value => (@fase.orcamento if (!@fase.nil? && !@fase.new_record?))%>
          <p class="help-block" style="font-size: 11px;">Insira o orçamento do custo. Obrigatório.</p>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :inicio_periodo,:class => "col-xs-6 col-sm-3 col-md-2 control-label" %>
        <div class="col-sm-4">
          <%= f.text_field :inicio_periodo, :class => "form-control","data-validate" => "validate(dateBR_required)", :title => "O início do período da fase deve ser inserido", :value => (@fase.inicio_periodo if (!@fase.nil? && !@fase.new_record?))%>
          <p class="help-block" style="font-size: 11px;">Insira a data de início prevista da fase. Obrigatório.</p>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :fim_periodo,:class => "col-xs-6 col-sm-3 col-md-2 control-label" %>
        <div class="col-sm-4">
          <%= f.text_field :fim_periodo, :class => "form-control","data-validate" => "validate(dateBR_required)", :title => "O fim do período da fase deve ser inserido", :value => (@fase.fim_periodo if (!@fase.nil? && !@fase.new_record?))%>
          <p class="help-block" style="font-size: 11px;">Insira a data de fim prevista da fase. Obrigatório.</p>
        </div>
      </div>


      <br>

      <div class="col-sm-2 col-md-11">
        <div class="well well-sm">
          <%= link_to 'Voltar', :back, :class => 'btn btn-warning' %>
          <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
        </div>
      </div>
    </fieldset>



<script type="text/javascript">



    $( document ).ready(function() {

        $("[id=fase_orcamento]").priceFormat({
            prefix: "R$ ",
            centsSeparator: ",",
            thousandsSeparator: ".",
            clearPrefix: true
        });

        $("[id*=_periodo]").mask("99/99/9999");


        $("[id=fase_orcamento_show]").priceFormat({
            prefix: "R$ ",
            centsSeparator: ",",
            thousandsSeparator: "."
        });
    });
</script>

app/views/fases/_new_fase.html.erb
<div id="new-fase-nova" aria-hidden="true" role="dialog" aria-labelledby="meuModal_nova" class="modal" style="display: none;">
  <%#= simple_form_for(@fase_nova, :url => fase_path(@fase_nova),:html => {:class => 'form-horizontal' })  do |f| %>
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <a class="close" data-dismiss="modal">&#215;</a>
            <h3 class="modal-title" id="meuModal_nova">Nova Fase</h3>
          </div>
            <%= form_for @fase_nova, :html => {:class => 'form-horizontal' } do |f| %>
              <div class="modal-body">
                <%= render :partial => 'form',:locals => { :f => f, :role => @role } %>
                </div>
            <% end %>

  <%# end %>
  </div>
  </div>
</div>

<script type="text/javascript">
    $( document ).ready(function() {
        $('#new-fase-nova').ketchup();
    });

</script>

app/views/fases/edit.html.erb
<ol class="breadcrumb">
  <li><a href="<%= root_path%>">Principal</a></li>
  <li><%= link_to "Fases", fases_path%></li>
  <li class="active">Cadastrar Fase</li>
</ol>
<%= painel_titulo("Fase - #{@fase.descricao}").html_safe%>
<div class="panel-body" id="form">

  <div class="row">
    <div class="col-md-10"> <%= exibe_erros(@fase).html_safe if @fase.errors.any?%></div>
  </div>
  <p>

<%= form_for @fase, :html => {:class => 'form-horizontal',:role => 'form' } do |f| %>

    <%= render :partial => 'form',:locals => { :f => f, :role => @role } %>

<%end%>

</p>
</div>

<script type="text/javascript">
    $( document ).ready(function() {
        //$("#custos_table").createFilter();
        $('[role=form]').ketchup();
        $("[id*=periodo]").mask("99/99/9999");
    });
</script>

app/views/fases/index.html.erb
#encoding: utf-8
<ol class="breadcrumb">
  <li><a href="<%= root_path%>">Principal</a></li>
  <li class="active">Fases</li>
</ol>
<%= painel_titulo("Fases").html_safe %>
<div class="panel-body">
  <div class="span8">
    <div class="well">
    <%= form_tag pesquisar_fases_path,:method => :get, :class => 'form-horizontal' , :role => 'form' do |f| %>
          <div class="row">
        <div class="form-group">
          <%= label_tag :filtro, "Filtro:",:class => "col-xs-3 control-label" %>
          <div class="col-xs-4">
            <%= text_field_tag :filtro, (@termo if @termo),{:placeholder => "Insira um termo para pesquisar", :class => "form-control","data-validate" => "validate(minlength(0))"}%>
          </div>
          </div>
        </div>
          <div class="row">
          <div class="form-group">
            <%= label_tag :inicio_periodo, "Período:",:class => "col-xs-3 control-label" %>
          <div class="col-xs-2">
            <%= text_field_tag :inicio_periodo, (params[:inicio_periodo] if params[:inicio_periodo]),{:placeholder => "Periodo início", :class => "form-control","data-validate" => "validate(dateBR)"}%>
          </div>
          <div class="col-xs-2">
            <%= text_field_tag :fim_periodo, (params[:fim_periodo] if params[:fim_periodo]),{:placeholder => "Período fim", :class => "form-control","data-validate" => "validate(dateBR)"}%>
          </div>

          <div class="col-xs-3">
            <%= submit_tag 'Pesquisar', :class => 'btn btn-primary' %>
          </div>
          </div>
          </div>
    <%end%>
    </div>


    <div class="table-responsive">
      <table class="table table-condensed table-striped table-hover" id="fase_table">
        <thead>
        <tr>
          <th>Número</th>
          <th>Curso</th>
          <th>Descrição</th>
          <th>Orçamento</th>
          <th>Data Início Prevista</th>
          <th>Data Fim Prevista</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <%if !@fases.blank?%>
        <%@fases.each do |fase|%>
        <tr>
        <td><%= link_to fase.id, fase%></td>
        <td><%=link_to fase.curso.nome, fase.curso%></td>
        <td><%= fase.descricao%></td>
        <td><div id="fase_orcamento_show"><%=fase.orcamento%></div></td>
          <% p fase.inicio_periodo if fase.inicio_periodo%>
          <% p fase.fim_periodo if fase.fim_periodo%>
        <td><%=l fase.inicio_periodo.to_date if fase.inicio_periodo%></td>
        <td><%=l fase.fim_periodo.to_date if fase.fim_periodo%></td>
        <td class="col-md-3"><span class="row"><%= link_to("Detalhar", fase_path(fase), :class => 'btn btn-xs btn-default')%>
          <%= link_to 'Editar', edit_fase_path(fase), :class => "btn btn-xs btn-primary "%>
          <%= link_to 'Excluir', fase_path(fase), :method => "delete", :class => "btn btn-xs btn-danger ", :data => {:confirm => (fase.custos.count > 0 ? "Existem custos atrelados a esta fase. Tem certeza que deseja excluir a fase <strong>#{fase.descricao.mb_chars.upcase}</strong>?" : "Tem certeza que deseja excluir a fase <strong>#{fase.descricao.mb_chars.upcase}</strong>?")}%></span></td>
        </tr>
            <%end%>
        <%else%>
                <tr>
        <td>Nenhum registro encontrado</td>
        </tr>
        <%end%>
        </tbody>
      </table>
      <div align="right"><%= (will_paginate @fases,:remote => true,:renderer => BootstrapPagination::Rails) if !@fases.blank?%></div>
      <div class="row">
        <a data-toggle="modal" class="btn btn-success" href="#new-fase-nova"  type="button">Nova Fase</a>
        <%= render "fases/new_fase"%>
      </div>
    </div>
  </div>
</div>
</div>

<script type="text/javascript">
    $( document ).ready(function() {
          //$("#custos_table").createFilter();
        $( document ).ready(function() {
            $("#fase_table").tablesorter({theme : "bootstrap",
                dateFormat: 'uk',
                widthFixed: true,
                headers: {
                    // set "sorter : false" (no quotes) to disable the column
                    0: {
                        sorter: "digit"
                    },
                    1: {
                        sorter: "text"
                    },
                    2: {
                        sorter: "text"
                    },
                    3: {
                        sorter: "text"
                    },
                    4: {
                        sorter: "shortDate"
                    },
                    5: {
                        sorter: "shortDate"
                    },
                    6: {
                        sorter: false,
                        filter: false
                    },
                    7: {
                        sorter: false,
                        filter: false
                    }
                },
                headerTemplate : '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!
                widgets : [ "uitheme", "filter" ],
                ignoreCase: true,
                widgetOptions : {
                    zebra : ["even", "odd"],
                    filter_reset : ".reset"
                }            });
        });
        $('[role=form]').ketchup();
        $("[id*=periodo]").mask("99/99/9999");
        });
</script>

app/views/fases/new.html.erb
# encoding: utf-8
<ol class="breadcrumb">
  <li><a href="<%= root_path%>">Principal</a></li>
  <li><%= link_to "Fases", custos_path%></li>
  <li>Novo fase</li>
</ol>
<%= painel_titulo("Cadastro de Fases").html_safe %>
<div class="panel-body">

  <div class="row">
    <div class="col-md-10"> <%= exibe_erros(@fase).html_safe if @fase.errors.any?%></div>
  </div>
  <p>
    <%= form_for @fase, :html => {:class => 'form-horizontal' } do |f| %>

        <%= render :partial => 'form',:locals => { :f => f, :role => @role } %>


  <% end %>


</div>
</div>

<script type="text/javascript">
    $( document ).ready(function() {
        $('#new_fase').ketchup();


    });
</script>

app/views/fases/show.html.erb
# encoding: utf-8
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<ol class="breadcrumb">
  <li><a href="<%= root_path%>">Principal</a></li>
  <li><%= link_to "Fases", fases_path%></li>
  <li class="active"><%= @fase.descricao%></li>
</ol>
<%if @custo_excedido%>
    <div class="alert alert-warning">Atenção! O orçamento previsto para esta fase do projeto foi ultrapassado.</div>
<%end%>
<%= painel_titulo("Fase - #{@fase.descricao}").html_safe %>
<%= render "categorias/new_categoria"%>
<div class="panel-body" id="form">
  <div class="row">
    <div class="col-md-offset-10"> <%= link_to "Editar", edit_fase_path(@fase), :class => "label label-primary "%>
    <%= link_to "Excluir", fase_path(@fase), :method => "delete", :class => "label label-danger ", :style => "margin-left:7px;", :data => {:confirm => (@fase.custos.count > 0 ? "Existem custos atrelados a esta fase. Tem certeza que deseja excluir a fase <strong>#{@fase.descricao}</strong>?" : "Tem certeza que deseja excluir a fase <strong>#{@fase.descricao}</strong>?")}%></div>
  </div>
  <fieldset>
    <h2>Dados</h2>
      <p><b>Descrição:</b> <%= @fase.descricao %></p>
      <p><b>Curso: </b><%= @fase.curso.nome%></p>
      <p><b>Data Início Prevista: </b><%= l @fase.inicio_periodo.to_date if @fase.inicio_periodo%></p>
      <p><b>Data Fim Prevista: </b><%= l @fase.fim_periodo.to_date if @fase.inicio_periodo%></p>
  </fieldset>
  </br>
  <fieldset>
    <h2>Custos</h2>
    <div class="row">
      <div class="col-md-offset-10"> <a data-toggle="modal" class="label label-success" href="#new_custo" type="button">Novo Custo</a>

      </div>
    </div>
    <%if @custo_excedido%>
        <p><b>Orçamento:</b><span id="fase_orcamento_show"><%= @fase.orcamento%></span> <span span id="fase_orcamento_show1" style="color: #ff0000" data-container="body" data-toggle="popover" data-placement="right" data-trigger="hover" data-content="Orçamento excedido em <%= number_to_currency(@valor_excedido.to_s[0,@valor_excedido.to_s.length-2]+","+@valor_excedido.to_s[@valor_excedido.to_s.length-2,2])%>" class='glyphicon glyphicon-warning-sign'></span></p>
    <%else%>
        <p><b>Orçamento:</b> <span id="fase_orcamento_show"><%= @fase.orcamento %></span></p>
    <%end%>
    <p><b>Custo total: </b><span id="fase_orcamento_show"><%= @fase.custos.sum('(valor*quantidade)+(valor*quantidade*tributo)/100')%></span></p>

    <%if @fase.custos.any?%>

        <%#= high_chart("my_id2", @chart2) %>
        <%#= pie_chart @fase.custos.joins(:categoria).group("categorias.descricao").count
        Custo.where(:categoria_id => custo.categoria.id).order('dt_referencia asc').group("categoria_id,dt_referencia").count%>
        <%= pie_chart @fase.custos.joins(:categoria).group("categorias.descricao").count %>


        <%= line_chart @fase.custos.collect(&:categoria).uniq.map{|c|
             {:name => c.descricao, :data => c.custos.group("to_char(dt_referencia,'DD/MM/YYYY')").count}
           }
        %>
        <fieldset>
          <h2>Lista de custos</h2>
        <div class="table-responsive" >
          <table class="table table-condensed table-striped table-hover tabela" data-sortlist="[[0,0],[2,0]]">
            <thead>
            <tr>
              <th>Número</th>
              <th>Data de Referência</th>
              <th>Categoria</th>
              <th>Valor</th>
            </tr>
            </thead>
            <tbody>
            <%@fase.custos.each do |custo|%>
                <tr>
                  <td><%=link_to custo.id, custo%></td>
                  <td><%=l custo.dt_referencia.to_date%></td>
                  <td><%=custo.categoria.descricao%></td>
                  <td><div id="fase_orcamento_show"><%=custo.tributo.nil? ? (custo.valor * custo.quantidade) : ((custo.valor * custo.quantidade)+(custo.valor * custo.quantidade * custo.tributo)/100)%></div></td>
                </tr>
            <%end%>

            </tbody>
          </table>
            </div>
        </fieldset>
          <div align="right"><%= will_paginate @custos_associados,:remote => true,:renderer => BootstrapPagination::Rails %></div>
    <%else%>
        <h6>Esta fase do projeto ainda não possui custos associados.</h6>
    <%end%>
  </fieldset>

  </br>
  <div class="well well-sm">
    <%= link_to 'Voltar', :back, :class => 'btn btn-warning' %>

  </div>

</div>
</div>

         <%= render "custos/new_custo"%>
<script type="text/javascript">



    $( document ).ready(function() {
        $("[id=fase_orcamento_show]").priceFormat({
            prefix: "R$ ",
            centsSeparator: ",",
            thousandsSeparator: "."
        });
        $(".tabela").tablesorter();


        $("#fase_orcamento_show1").priceFormat({
            prefix: "R$ ",
            centsSeparator: ",",
            thousandsSeparator: "."
        });
        $('#fase_orcamento_show1').popover('toggle')
        $('#new-categoria')
                .on('hidden.bs.modal', function() {
            $('#new_custo').css('opacity', 1);})
                .on('show.bs.modal', function() {
                $('#new-categoria').css('z-index','9999');
                $('#new_custo').css('opacity',.5);
        });


    });




</script>