config/routes.rb
RailsPadrao::Application.routes.draw do


  resources :categorias


  resources :custos

  resources :arquivos


  resources :cursos do
    member do
      get :download
    end
  end

  resources :relatorios do
    collection do
      get :relatorio_fase_custos
      post :exporta_relatorio
    end
  end


  root :to => 'application#home'
  authenticated :user do
    root :to => 'application#home'
  end
  resources :noticias do
    member do
      get :like
      get :dislike
      get :remover_voto
      post :criar_comentario
    end

    collection do
      get :feed
      get :buscar_tag
    end
  end

  devise_for :users do
    get 'users/:id/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'

  end

  resources :users do
    collection do
      get 'novo_usuario_manual'
      post 'cria_usuario_manualmente'
    end
  end

  resource :users, :only => [:edit] do
    member do
      post ':id/atualizar' => 'users#atualiza_usuario_com_senha', :as => "atualiza_usuario_com_senha"
    end
  end

  resources :roles do
    collection do
      get 'associar_permissao'
    end
  end

  resources :permissions

  resources :permission_role do
    collection do
      post 'remove_permissao_ajax'
      post 'adiciona_permissao_ajax'
    end
  end

  resources :fases do
    collection do
      get 'pesquisar'
    end

  end


end

app/models/role.rb
class Role < ActiveRecord::Base
  #has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  has_many :user_roles
  has_many :users, :through => :user_roles
  has_many :noticia_permissoes, :dependent => :destroy
  has_many :permission_roles
  has_many :permissions,  :through => :permission_roles

  accepts_nested_attributes_for :permissions

  validates :name, {:presence => true, :uniqueness => true}
  before_destroy :tratar_usuarios_orfaos,:evitar_delecao_visitante

  scopify

  VISITANTE = "Visitante"
  ADMIN = "Admin"

  attr_accessible :name

def self.permissoes_associadas
  Role.find_each do |r| @a = r.permissions end
  return @a
end


  def overpower?
    return true if self.name == ADMIN
  end



  #Todos os usuários terão seu grupo alterado pra visitante, se um grupo for deletado
  def tratar_usuarios_orfaos
    UserRole.update_all({:role_id => Role.where(:name => VISITANTE).first},{:role_id => self})
  end

  def evitar_delecao_visitante
    return false if self.name == VISITANTE
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  load_and_authorize_resource


  def index
    @role = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @role }
    end
  end

  # GET /Role/1
  # GET /Role/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json =>@role }
    end
  end

  # GET /Role/new
  # GET /Role/new.json
  def new
    @role = Role.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json =>@role }
    end
  end

  # GET /Role/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /Role
  # POST /Role.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to roles_path, :notice => "Grupo #{@role.name} criado com sucesso." }
        format.json { render json =>@role, status =>:created, location =>@role }
      else
        format.html { render :action =>"new" }
        format.json { render json =>@role.errors, status =>:unprocessable_entity }
      end
    end
  end

  # PUT /Role/1
  # PUT /Role/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, :notice => "Grupo #{@role.name} atualizado com sucesso."}
        format.json { head :no_content }
      else
        format.html { render :action =>"edit" }
        format.json { render json =>@role.errors, status =>:unprocessable_entity }
      end
    end
  end

  # DELETE /Role/1
  # DELETE /Role/1.json
  def destroy
    @role = Role.find(params[:id])
    nome = @role.name
    binding.pry
    respond_to do |format|
      if @role.destroy
        format.html { redirect_to roles_path, :notice => "Grupo #{nome} removido com sucesso." }
        format.json { head :no_content }
      else
        format.html { redirect_to roles_path, :alert => "Erro ao remover grupo #{nome}: #{@role.errors.full_messages.to_s}" }
        format.json { head :no_content }
      end
    end
  end

  def associar_permissao
    @permissions = Permission.all
    @roles = Role.all
    @rb = PermissionRole.all

  end


end

app/views/roles/_form.html.erb
# encoding: utf-8

<div class="form-group">
  <%= f.label :name, "Nome:",:class => "col-xs-6 col-sm-3 col-md-2 control-label" %>
  <div class="col-sm-2 col-md-3">
    <%= f.text_field :name, :value => @role.name,:class => "form-control","data-validate" => "validate(required)", :autofocus => true,:title => "Nome do grupo",:placeholder => "Insira o nome do grupo"%>
    <p class="help-block" style="font-size: 11px;">Insira seu nome. Obrigatório.</p>
  </div>
</div>

app/views/roles/associar_permissao.html.erb
# encoding: utf-8

<ol class="breadcrumb">
  <li><a href="<%= root_path%>">Principal</a></li>
  <li>Grupos</li>
  <li class="active">Permissões</li>
</ol>
<%= painel_titulo("Associar permissões").html_safe %>
<%= form_for @rb, :html => {:class => 'form-horizontal' } do |f| %>
<div class="panel-body">
  <div class="span8">
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
        <tr>
          <th>Grupo</th>
              <% @permissions.each do |permission| %>
              <th><%= permission.subject_class %></th>
             <%end%>
        </tr>
        </thead>
        <tbody>
        <tr>
              <% @roles.each do |role| %>
                  <td><%= link_to role.name, role %></td>
                  <% @permissions.each do |permission| %>
                      <%if @rb.collect {|a| a.permission_id == permission.id && a.role_id == role.id}%>

                          <td><%= %></td>
                      <%else%>
                          <td><div class="checkbox">
                            <label>
                              <input type="checkbox"><%= permission.action%>
                            </label></div></td>

                      <%end%>

            <% end %>
        <% end %>
        </tr>
        </tbody>
      </table>
    </div>
    <%= link_to 'Novo grupo', new_role_path, :class => 'btn btn-success'  %>
  </div>
</div>
</div>

app/views/roles/edit.html.erb
# encoding: utf-8

<ol class="breadcrumb">
<li><a href="<%= root_path%>">Principal</a></li>
<li><%= link_to "Grupos", roles_path%></li>
<li class="active">Editar grupo</li>
</ol>
<%= painel_titulo("Editar grupo").html_safe %>
<div class="panel-body">

<div class="row">
<div class="col-md-10"> <%= exibe_erros(@role).html_safe if @role.errors.any?%></div>
  </div>
  <p>
    <%= form_for @role, :html => {:class => 'form-horizontal' } do |f| %>

        <%= render :partial => 'form',:locals => { :f => f, :role => @role } %>
      <div class="form-group">
        <div class="col-sm-2 col-md-offset-3">
          <%= f.submit 'Editar', :class => 'btn-primary' %>
        </div>
      </div>
<% end %>


</div>
</div>

<script type="text/javascript">
$( document ).ready(function() {
  $('#edit_role').ketchup();
});
</script>

app/views/roles/index.html.erb
# encoding: utf-8

<ol class="breadcrumb">
  <li><a href="<%= root_path%>">Principal</a></li>
  <li class="active">Grupos</li>
</ol>
<%= painel_titulo("Grupos").html_safe %>
<div class="panel-body">
  <div class="span8">
    <div class="table-responsive">
      <table class="table table-condensed table-striped table-hover">
        <thead>
        <tr>
          <th>Grupo</th>
          <th>Data de Cadastro</th>
          <th>Quantidade de pessoas</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @roles.each do |role| %>
            <tr>
              <td><%= link_to role.name, role %></td>
              <td><%= role.created_at.to_date if !role.created_at.blank?%></td>
              <td><%= link_to role.users.count.to_s, users_path%></td>
              <td><%= link_to("Editar", edit_role_path(role), :style => "margin-top:-7px;", :class => 'btn btn-xs btn-default')%></td>
              <td><%= link_to("Remover", role_path(role), :style => "margin-top:-7px;", :data => { :confirm => "Você tem certeza?\nSe houver algum usuário associado a este grupo, o mesmo será associado ao grupo Visitante automaticamente." }, :method => :delete, :class => 'btn btn-xs btn-danger')%></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to 'Novo grupo', new_role_path, :class => 'btn btn-success'  %>
  </div>
</div>
</div>

app/views/roles/show.html.erb
<ol class="breadcrumb">
  <li><a href="<%= root_path%>">Principal</a></li>
  <li><%= link_to "Grupos", roles_path%></li>
  <li class="active">Grupo <%=@role.name%></li>
</ol>
<%= painel_titulo("Grupo - #{@role.name}").html_safe %>
<div class="panel-body">
  <div class="row">
    <div class="col-md-offset-10"> <%= link_to "Remover grupo", role_path(@role), :data => { :confirm => "Tem certeza que deseja excluir este grupo?" }, :method => :delete, :class => "label label-danger "%></div>
  </div>

  <div class="form-group">
    <p><b>Nome:</b> <%= @role.name %></p>
    <p><b>Data de cadastro: </b><%= @role.created_at.to_date %></p>
  </div>

</div>
</div>